[versions]
androidGradlePlugin = "8.6.1"
androidx-coreKtx = "1.13.1"
androidx-activity-compose = "1.9.2"
androidx-compose-material3 = "1.3.0"
androidx-navigation-compose = "2.8.1"
ezXHelper = "2.2.0"
kotlin = "2.0.20"
lyricGetterApi = "6.0.0"
miuix = "0.2.3"
xposed = "82"


[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation-compose" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }
lyricGetterApi = { module = "com.github.xiaowine:Lyric-Getter-Api", version.ref = "lyricGetterApi" }
miuix = { module = "top.yukonga.miuix.kmp:miuix", version.ref = "miuix" }
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
