name: Android CI Dev

on:
  push:
    branches: [Dev, new]
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Write key
        if: ${{ github.event_name != 'pull_request' || github.ref_type == 'tag' }}
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo androidStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
            echo androidKeyAlias='xiao_wine' >> local.properties
            echo androidKeyPassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
            echo androidStoreFile=`pwd`/key.jks >> local.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks
          fi

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "microsoft"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/new' }}

      - name: Build with Gradle
        run: |
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx4g' >> gradle.properties
          ./gradlew assemble
          ./gradlew bundleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: StatusBarLyric_release
          path: ./app/build/outputs/apk/release

      - name: Upload Release AAB APK
        uses: actions/upload-artifact@v3
        with:
          name: StatusBarLyric_aab
          path: ./app/build/outputs/bundle/release

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: StatusBarLyric_debug
          path: ./app/build/outputs/apk/debug

      - name: Upload Release Mapping
        uses: actions/upload-artifact@v3
        with:
          name: StatusBarLyric_release_mapping
          path: ./app/build/outputs/mapping/release/mapping.txt